/**
 * PDF 生成器
 *
 * 实现 Exporter 接口，将政策简报导出为 PDF 格式
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { Exporter, PolicyBriefExportData } from './types'

// ==================== PDF 生成器 ====================

export class PDFGenerator implements Exporter<PolicyBriefExportData> {
  readonly name = 'PDF'
  readonly extension = '.pdf'
  readonly mimeType = 'application/pdf'

  /**
   * 导出政策简报为 PDF
   */
  async export(data: PolicyBriefExportData): Promise<Uint8Array> {
    return this.generatePolicyBriefPDF(data)
  }

  /**
   * 生成政策简报 PDF（兼容旧接口）
   */
  async generatePolicyBriefPDF(data: PolicyBriefExportData): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create()

    // 添加字体（使用内置字体）
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    // 创建页面
    const page = pdfDoc.addPage([595.28, 841.89]) // A4 尺寸

    // 设置边距
    const margin = 50

    // 标题
    page.drawText('Policy Brief', {
      x: margin,
      y: page.getHeight() - margin - 30,
      size: 24,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    })

    // 简报标题
    page.drawText(data.title, {
      x: margin,
      y: page.getHeight() - margin - 70,
      size: 18,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.2),
    })

    let y = page.getHeight() - margin - 110

    // 辅助函数：绘制文本块
    const drawSection = (title: string, content: string) => {
      // 标题
      page.drawText(title, {
        x: margin,
        y,
        size: 14,
        font: boldFont,
        color: rgb(0.1, 0.1, 0.1),
      })
      y -= 25

      // 内容（简单换行处理）
      const lines = this.wrapText(content, 80)
      for (const line of lines) {
        if (y < margin + 50) {
          // 添加新页面
          const newPage = pdfDoc.addPage([595.28, 841.89])
          y = newPage.getHeight() - margin - 30
        }

        page.drawText(line, {
          x: margin + 10,
          y,
          size: 10,
          font,
          color: rgb(0.3, 0.3, 0.3),
        })
        y -= 15
      }
      y -= 15
    }

    // 生成时间
    page.drawText(`Generated: ${data.generatedAt.toLocaleDateString('zh-CN')}`, {
      x: margin,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    })
    y -= 20

    page.drawText(`By: ${data.generatorName}`, {
      x: margin,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    })
    y -= 30

    // 摘要
    drawSection('Summary', data.summary)

    // 适用对象
    drawSection('Applicable To', data.applicableTo)

    // 关键条款
    drawSection('Key Clauses', data.keyClauses)

    // 行动建议
    drawSection('Action Suggestions', data.actionSuggestions)

    // 风险提醒
    drawSection('Risk Reminders', data.riskReminders)

    // 来源链接
    page.drawText('Source:', {
      x: margin,
      y,
      size: 10,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    })
    y -= 15
    page.drawText(data.sourceUrl, {
      x: margin + 10,
      y,
      size: 8,
      font,
      color: rgb(0, 0, 0.8),
    })

    // 页脚
    page.drawText('Generated by Evercog MVP', {
      x: margin,
      y: margin,
      size: 8,
      font,
      color: rgb(0.5, 0.5, 0.5),
    })

    // 保存 PDF
    return pdfDoc.save()
  }

  /**
   * 文本换行
   */
  private wrapText(text: string, maxLength: number): string[] {
    const lines: string[] = []
    const paragraphs = text.split('\n')

    for (const paragraph of paragraphs) {
      if (paragraph.length <= maxLength) {
        lines.push(paragraph)
      } else {
        // 简单换行
        let remaining = paragraph
        while (remaining.length > maxLength) {
          const breakPoint = remaining.lastIndexOf('，', maxLength) ||
                           remaining.lastIndexOf('。', maxLength) ||
                           remaining.lastIndexOf('；', maxLength) ||
                           maxLength
          lines.push(remaining.substring(0, breakPoint + 1))
          remaining = remaining.substring(breakPoint + 1)
        }
        if (remaining) {
          lines.push(remaining)
        }
      }
    }

    return lines
  }
}

// ==================== 单例导出 ====================

let _pdfGenerator: PDFGenerator | null = null

export function getPDFGenerator(): PDFGenerator {
  if (!_pdfGenerator) {
    _pdfGenerator = new PDFGenerator()
  }
  return _pdfGenerator
}
